objects:
  - name: bottle
    type: cylinder           # future: box | sphere
    frame_id: world
    pose:
      position: [1.203, 0.3028, 0.115]      # x, y, z
      orientation: [1.0, 0.0, 0.0, 0.0] # w, x, y, z
    dimensions: [0.23, 0.04]            # cylinder: [height, radius]

  - name: flask
    type: cylinder
    frame_id: world
    pose:
      position: [0.876, 0.4198, 0.115]
      orientation: [1.0, 0.0, 0.0, 0.0]
    dimensions: [0.23, 0.045]

  - name: fixture1
    type: compound
    frame_id: world
    base_pose:                      # optional base transform for the whole object
      position: [0.80, 0.00, 0.40]  # x, y, z
      orientation: [1, 0, 0, 0]     # w, x, y, z
    components:
      - type: box
        dimensions: [0.6, 0.4, 0.02]
        pose: { position: [0, 0, 0], orientation: [1,0,0,0] }
      - type: cylinder
        dimensions: [0.40, 0.03]    # [height, radius]
        pose: { position: [0.25,  0.15, -0.20], orientation: [1,0,0,0] }
      - type: cylinder
        dimensions: [0.40, 0.03]
        pose: { position: [0.25, -0.15, -0.20], orientation: [1,0,0,0] }
      - type: sphere
        dimensions: [0.05]          # [radius]
        pose: { position: [-0.20, 0.0, 0.05], orientation: [1,0,0,0] }